# Generated by Django 5.0.6 on 2024-06-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(choices=[('n', 'black - n'), ('a', 'blue - a'), ('d', 'red - d'), ('e', 'creamy - e'), ('f', 'black tortoiseshell - f'), ('g', 'blue tortoiseshell - g'), ('s', 'silver/smoky - s'), ('w', 'white - w')], default='n', max_length=1)),
                ('drawing_code', models.CharField(choices=[('11', 'shaded - 11'), ('12', 'shell - 12'), ('21', 'unspecified drawing - 21'), ('22', 'marble drawing (blotched - 22)'), ('23', 'tiger drawing (mackerel - 23)'), ('24', 'dot drawing (spotted - 24)'), ('25', 'ticked drawing (ticked - 25)')], default='11', max_length=2)),
                ('white_mottle_code', models.CharField(choices=[('01', 'from - 01'), ('02', 'harlequin - 02'), ('03', 'bicolor - 03'), ('09', 'with unspecified white spots - 09')], default='01', max_length=2)),
                ('eye_color_code', models.CharField(choices=[('61', 'blue eyes - 61'), ('62', 'orange/amber eyes - 62'), ('63', 'unevenly colored eyes (odd eyed) - 63'), ('64', 'green eyes - 64')], default='61', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothers_name', models.CharField(max_length=100)),
                ('mothers_breeder', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_breeder', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats_name', models.CharField(max_length=255)),
                ('breeder_name', models.CharField(max_length=255)),
                ('color', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cats.color')),
                ('parents_name', models.ManyToManyField(to='cats.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats_name', models.CharField(max_length=255)),
                ('breeder_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
                ('color', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cats.color')),
                ('parents_name', models.ManyToManyField(to='cats.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Tomcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats_name', models.CharField(max_length=255)),
                ('breeder_name', models.CharField(max_length=255)),
                ('color', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cats.color')),
                ('parents_name', models.ManyToManyField(to='cats.parent')),
            ],
        ),
    ]
