# Generated by Django 5.0.6 on 2024-06-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_kitten_birth_date_tomcat_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Home',
        ),
    ]
