# Generated by Django 5.0.6 on 2024-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats_photos/'),
        ),
        migrations.AddField(
            model_name='tomcat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats_photos/'),
        ),
    ]
